### ISSUE TITLE
Clone Download Progress

### ISSUE THREAD

**Issue by rlaurente** [light-tech/LibGit2-On-iOS#3]
Hi

I just figured out the way to make this plugin work in m1 and it's really cool! Thanks. For the clone method, Do you have a callback that can determine the download progress ? Currently I only see and tested the checkout progress.

Thanks

**Comment by light-tech** [comment]
Cools. We don't own an M1 yet to test if it works or not.

> For the clone method, Do you have a callback that can determine the download progress ? Currently I only see and tested the checkout progress.

This is SwiftGit2's issue. If they don't have it (just like they never have other features like git push, ...), you must develop it yourself by:
1. Learn how to do it in `libgit2` via remote callbacks struct. (This requires C programming knowledge.)
2. Learn to write/translate C code in the above step into Swift via the official documentation https://github.com/apple/swift/blob/main/docs/HowSwiftImportsCAPIs.md

We are making our own package to avoid the second step.

**Comment by light-tech** [comment]
Our new Swift package MiniGit is [now available](https://github.com/light-tech/MiniGit).
