### ISSUE TITLE
libgit2 build failed.

### ISSUE THREAD

**Issue by i-tengfei** [light-tech/LibGit2-On-iOS#5]
run build-libgit2-framework.sh

Then I got the error as below

```
error:  cannot create libgit2-1.3.0/tests/resources/status/�+�
Illegal byte sequence
```

but openssl build succeeded.

**Comment by i-tengfei** [comment]
It seems to be an unzip error, there is an error when unzipping the path containing Chinese.
`libgit2-1.3.0/tests/resources/status/这`
https://github.com/light-tech/LibGit2-On-iOS/blob/3039e0d72b361bc0f08644a539b67860386a9d9d/build-libgit2-framework.sh#L170
`ditto -V -x -k --sequesterRsrc --rsrc v1.3.0.zip ./` works fine.

**Comment by light-tech** [comment]
Thanks for identifying the root cause of the issue. We have seen this error many times but since it does not affect the building process (after all, the script does not run the tests), we decided to ignore it 🙈
